site_name: Learning DBMS
site_author: 'zhoujiagen@gmail.com'
copyright: MIT
repo_name: learning-dbms
repo_url: https://github.com/zhoujiagen/learning-dbms

nav:
    - Home: index.md
    - 'Overview':
      - 'A First Course in Database Systems': overview/AFCDBMS.md
      - 'Database Internals':
        - 'Home': overview/database-internals/DI.md
        - 'References': overview/database-internals/DI-references.md
        - 'Storage Engines': overview/database-internals/DI-storage-engines.md
        - 'Distributed Systems': overview/database-internals/DI-distributed-systems.md
      - 'Designing Data-Intensive Applications':
        - 'Home': overview/DDIA.md
        - 'References': overview/DDIA-references.md
    - 'Data and File Formats':
      - 'Home': data-file-formats/index.md
      - 'Dynamic storage allocation': data-file-formats/dynamic_storage_allocation.md
      - 'File Structures(C++)': data-file-formats/file-structure/file-structures-cpp.md
      - 'File Structures(C++) B-tree': data-file-formats/file-structure/file-structures-cpp-btree.md
      - 'File Structures(C++) Hash': data-file-formats/file-structure/file-structures-cpp-hash.md
      - 'Algorithms and data structures for external memory': data-file-formats/algorithms_and_data_structures_for_external_memory.md
      - 'Examples':
        - 'MySQL':
          - 'Data Type': data-file-formats/examples/mysql/mysql-data-type.md
          - '.frm': data-file-formats/examples/mysql/mysql-frm-file-format.md
          - 'InnoDB Record and Page Structure': data-file-formats/examples/mysql/mysql-innodb-record-and-page-structure.md
          - 'Client/Server Protocol': data-file-formats/examples/mysql/mysql-client-server-protocol.md
          - 'Binary Log': data-file-formats/examples/mysql/mysql-binary-log.md
    - 'Query Processing':
      - Parse:
        - 'Modeling in RDFS and OWL': query/parse/rdfs_owl.md
        - 'SPARQL': query/parse/sparql.md
        - 'Logica': query/parse/logica.md
      - Optimization:
        - 'Query Optimization': query/optimization/query-optimization.md
    - 'Transaction':
      - 'Transaction Processing: Concepts and Techniques': transaction/TPCT.md
      - 'ARIES': transaction/aries.md
    - 'Implementations':
      - 'MySQL':
        - 'Manual':
          - 'MySQL Explain': implementation/mysql/manual/mysql-explain.md
          - 'MySQL InnoDB Locks': implementation/mysql/manual/mysql-innodb-locks.md
          - 'MySQL 5.7 Server Administration': implementation/mysql/manual/mysql-5.7-server-admin.md
          - 'MySQL 5.7 InnoDB Storage Engine': implementation/mysql/manual/mysql-5.7-innodb.md
          - 'MySQL 8.0 Manual': implementation/mysql/manual/mysql-8.0-manual.md
        - 'MySQL 5.7':
          - 'Home': implementation/mysql/mysql-5.7/mysql-index.md
          - 'Static':
            - 'Server':
              - 'Home': implementation/mysql/mysql-5.7/static/server/server-index.md
              - 'include': implementation/mysql/mysql-5.7/static/server/include.md
              - 'strings': implementation/mysql/mysql-5.7/static/server/strings-index.md
              - 'mysys': implementation/mysql/mysql-5.7/static/server/mysys-index.md
              - 'sql':
                - 'Home': implementation/mysql/mysql-5.7/static/server/sql/sql-index.md
                - 'auth': implementation/mysql/mysql-5.7/static/server/sql/auth/sql-auth.md
                - 'conn_handler': implementation/mysql/mysql-5.7/static/server/sql/conn_handler/sql-conn_handler.md
                - 'partitioning': implementation/mysql/mysql-5.7/static/server/sql/partitioning/sql-partitioning.md
                - 'share': implementation/mysql/mysql-5.7/static/server/sql/share/sql-share.md
            - 'Innobase':
              - 'Home': implementation/mysql/mysql-5.7/static/innobase/innobase-index.md
              - 'include': implementation/mysql/mysql-5.7/static/innobase/include.md
              - 'api': implementation/mysql/mysql-5.7/static/innobase/api.md
              - 'btr': implementation/mysql/mysql-5.7/static/innobase/btr.md
              - 'buf': implementation/mysql/mysql-5.7/static/innobase/buf.md
              - 'data': implementation/mysql/mysql-5.7/static/innobase/data.md
              - 'dict': implementation/mysql/mysql-5.7/static/innobase/dict.md
              - 'eval': implementation/mysql/mysql-5.7/static/innobase/eval.md
              - 'fil': implementation/mysql/mysql-5.7/static/innobase/fil.md
              - 'fsp': implementation/mysql/mysql-5.7/static/innobase/fsp.md
              - 'fts': implementation/mysql/mysql-5.7/static/innobase/fts.md
              - 'fut': implementation/mysql/mysql-5.7/static/innobase/fut.md
              - 'gis': implementation/mysql/mysql-5.7/static/innobase/gis.md
              - 'ha': implementation/mysql/mysql-5.7/static/innobase/ha.md
              - 'handler': implementation/mysql/mysql-5.7/static/innobase/handler.md
              - 'ibuf': implementation/mysql/mysql-5.7/static/innobase/ibuf.md
              - 'lock': implementation/mysql/mysql-5.7/static/innobase/lock.md
              - 'log': implementation/mysql/mysql-5.7/static/innobase/log.md
              - 'mach': implementation/mysql/mysql-5.7/static/innobase/mach.md
              - 'mem': implementation/mysql/mysql-5.7/static/innobase/mem.md
              - 'mtr': implementation/mysql/mysql-5.7/static/innobase/mtr.md
              - 'os': implementation/mysql/mysql-5.7/static/innobase/os.md
              - 'page': implementation/mysql/mysql-5.7/static/innobase/page.md
              - 'pars': implementation/mysql/mysql-5.7/static/innobase/pars.md
              - 'que': implementation/mysql/mysql-5.7/static/innobase/que.md
              - 'read': implementation/mysql/mysql-5.7/static/innobase/read.md
              - 'rem': implementation/mysql/mysql-5.7/static/innobase/rem.md
              - 'row': implementation/mysql/mysql-5.7/static/innobase/row.md
              - 'srv': implementation/mysql/mysql-5.7/static/innobase/srv.md
              - 'sync': implementation/mysql/mysql-5.7/static/innobase/sync.md
              - 'trx': implementation/mysql/mysql-5.7/static/innobase/trx.md
              - 'usr': implementation/mysql/mysql-5.7/static/innobase/usr.md
              - 'ut': implementation/mysql/mysql-5.7/static/innobase/ut.md
            - 'Performance Schema':
              - 'Home': implementation/mysql/mysql-5.7/static/perfschema/perfschema-index.md
              - 'cursor': implementation/mysql/mysql-5.7/static/perfschema/cursor.md
              - 'ha_perfschema': implementation/mysql/mysql-5.7/static/perfschema/ha_perfschema.md
              - 'pfs': implementation/mysql/mysql-5.7/static/perfschema/pfs.md
              - 'table': implementation/mysql/mysql-5.7/static/perfschema/table.md
          - 'Behaviour':
            - 'DBUG': implementation/mysql/mysql-5.7/behaviour/DBUG.md
            - 'Transaction': implementation/mysql/mysql-5.7/behaviour/trx.md
            - 'INSERT': implementation/mysql/mysql-5.7/behaviour/insert.md
            - 'SELECT': implementation/mysql/mysql-5.7/behaviour/select.md
            - 'INSERT INTO SELECT': implementation/mysql/mysql-5.7/behaviour/insert_into_select.md
        - 'MySQL 8.0':
          - 'Source Build': implementation/mysql/mysql-8.0/mysql_compile.md
          - 'mysqld': implementation/mysql/mysql-8.0/mysql_mysqld.md
          - 'Data Models': implementation/mysql/mysql-8.0/mysql_data_model.md
          - 'Routines': implementation/mysql/mysql-8.0/mysql_routines.md
          - 'InnoDB': implementation/mysql/mysql-8.0/mysql_innodb.md
      - 'Text and Graph':
          - 'WordNet': implementation/graph/wordnet.md
          - 'Lemon':  implementation/graph/lemon.md
          - 'An Introduction to Linguistics': implementation/graph/linguistics.md
          - 'Dgraph': implementation/graph/dgraph.md
          - 'JanusGraph': implementation/graph/janusgraph.md
          - 'Apache Jena': implementation/graph/jena.md
          - 'SPARQL': implementation/graph/sparql.md
          - 'AllegroGraph': implementation/graph/allegrograph.md
          - 'Apache Solr': implementation/graph/solr.md
          - 'Apache TinkerPop': implementation/graph/tinkerpop.md
          - 'ElasticSearch': implementation/graph/elasticsearch.md
          - 'Benchmark': implementation/graph/graph-benchmark.md
      - 'ClickHouse': implementation/clickhouse.md
      - 'Presto': implementation/presto.md

#theme: readthedocs
theme:
  name: material
extra:
  search:
    language: 'en'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.arithmatex # LaTeX math equations
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - markdown_inline_graphviz

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
